### ISSUE TITLE
词法分析中 “注释指导” 的问题

### ISSUE THREAD

**Issue by yiranyyu** [BUAA-SE-Compiling/miniplc0-compiler#1]
阅读[代码](https://github.com/BUAA-SE-Compiling/miniplc0-compiler/blob/ebc238d8facf7514de3eb29e6a3393e2bc57e29f/tokenizer/tokenizer.cpp)过程中发现两处问题

1. [无符号整数状态中读取到字母时的处理](https://github.com/BUAA-SE-Compiling/miniplc0-compiler/blob/ebc238d8facf7514de3eb29e6a3393e2bc57e29f/tokenizer/tokenizer.cpp#L129)
2. [关于 eof 的处理](https://github.com/BUAA-SE-Compiling/miniplc0-compiler/blob/ebc238d8facf7514de3eb29e6a3393e2bc57e29f/tokenizer/tokenizer.cpp#L126)

### 无符号整数状态中读取到字母

根据 [指导书](https://github.com/BUAA-SE-Compiling/miniplc0-handbook/tree/e264de3ccbd5f28720126a4b7d4fbcb6b29a5732#332-%E7%8A%B6%E6%80%81%E5%9B%BE)，在无符号整数状态下读取到字母应该不是”存储读到的字符并转移到标识符状态“，而是“回退并解析”， 比如 `123a` 应该被分析为 `123` 和 `a`，也就是在读取到 `a` 时回退一个字符并返回解析结果 `123`

### 关于 eof 的处理

按照 [实现](https://github.com/BUAA-SE-Compiling/miniplc0-compiler/blob/ebc238d8facf7514de3eb29e6a3393e2bc57e29f/tokenizer/tokenizer.cpp#L183) 缓冲区中只有在读取完最后一个 '\n' 后才会遇到 `isEOF()` 返回 `true` 的情况，而读取到 `\n` 一定意味着自动机状态不再是无符号整数了，也就是说在无符号整数状态下不会遇到 eof 。同样的问题也出现在标识符状态的注释中。

---

 [2019-11-09] 更新指导书链接为对应 permanent link

**Comment by fazdzz** [comment]
> ### 无符号整数状态中读取到字母
> 根据 [指导书](https://github.com/BUAA-SE-Compiling/miniplc0-handbook/blob/master/Readme.md#332-%E7%8A%B6%E6%80%81%E5%9B%BE)，在无符号整数状态下读取到字母应该不是”存储读到的字符并转移到标识符状态“，而是“回退并解析”， 比如 `123a` 应该被分析为 `123` 和 `a`，也就是在读取到 `a` 时回退一个字符并返回解析结果 `123`

这个地方从最开始我们内部就有点争议，我先解释一下背景：

C语言的[整数字面量](https://en.cppreference.com/w/cpp/language/integer_literal)和[浮点字面量](https://en.cppreference.com/w/cpp/language/floating_literal)有类型后缀这一说，比如 `1LL` 这里的 `LL` ，它说明这是一个 `long long` 类型的字面量。同样的在一个数字串后紧随 `e` 和 `E` 说明这是一个科学计数法描述的浮点字面量（后面应该还有指数部分）。而这些类型后缀的种类是有限的，其他后缀在 C 都会视为编译错误 `invalid suffix on constant`。

最开始设计 mini 的时候是希望尽可能地跟 C0 尽量接轨，所以我们保留了这个设定，mio将其解释为 [`invalid identifier`](https://github.com/BUAA-SE-Compiling/miniplc0-compiler/blob/ebc238d8facf7514de3eb29e6a3393e2bc57e29f/error/error.h#L25) 。但是 mini 又没有类型系统，这样一个编译错误会显得有点怪，所以最开始就存在这样的争议。

这里涉及到编译器如何解释/推测编译错误发生的原因，在实现上可能会考虑语法分析的上下文（分析为 `123` 和 `a`，根据 `a` 被获取的语境决定是什么错误），也可能就只让词法分析程序发现这个问题（`123a`），是一个比较主观的事情。在指导书[对修改的要求](https://github.com/BUAA-SE-Compiling/miniplc0-handbook/blob/master/Readme.md#3833-%E5%AF%B9%E4%BF%AE%E6%94%B9%E7%9A%84%E8%A6%81%E6%B1%82)中，提到了编译错误是**可以自己修改**的，因此这里你完全可以选择你认为更合适的方式来实现。这里的注释的确是我们对这种情况处理方式的主观看法，之后等 mio 下班会讨论一下要不要改/如何改。

> ### 关于 eof 的处理
> 按照 [实现](https://github.com/BUAA-SE-Compiling/miniplc0-compiler/blob/ebc238d8facf7514de3eb29e6a3393e2bc57e29f/tokenizer/tokenizer.cpp#L183) 缓冲区中只有在读取完最后一个 '\n' 后才会遇到 `isEOF()` 返回 `true` 的情况，而读取到 `\n` 一定意味着自动机状态不再是无符号整数了，也就是说在无符号整数状态下不会遇到 eof 。同样的问题也出现在标识符状态的注释中。

写的没问题的话好像的确不会在 `INITIAL_STATE` 之外的情况碰到 eof 。关于具体实现的问题，等 mio 回复吧。

**Comment by wtdcode** [comment]
感谢参与实验设计，首先这个勘误是有效的，这里指导书和源代码出现了不一致，请按照要求发送邮件方便我们归档 @yiranyyu

第一个问题挺烦的，目前实现（或者说期望大家的实现）是把这种错误在词法分析消灭，比如[这里](https://github.com/BUAA-SE-Compiling/miniplc0-compiler/blob/ebc238d8facf7514de3eb29e6a3393e2bc57e29f/tokenizer/tokenizer.cpp#L171)，我的意见是改指导书的状态机图。

第二个问题我再看看。

BTW，引用指导书请按照首页写的引用 permanent link

**Comment by wtdcode** [comment]
第二个问题更新状态机图后是不是已经没有了？

如果还有问题请记得 reopen。
