### ISSUE TITLE
一点小勘误

### ISSUE THREAD

**Issue by LemonForeast** [BUAA-SE-Compiling/miniplc0-compiler#10]
https://github.com/BUAA-SE-Compiling/miniplc0-compiler/blob/master/tokenizer/tokenizer.cpp#L138
这里描述是“字符或字母”，但显然字符是包含字母的，结合这一段的实际作用，我猜这里应该是想说“数字或字母”？

**Comment by wtdcode** [comment]
快速扫了眼可能是的，晚点我再确认一下。

BTW，引用的话请 permanent links

________________________________

**Comment by yuanzilin** [comment]
所以助教确认完了没有？

**Comment by wtdcode** [comment]
诚实的说，忘了

________________________________

**Comment by wtdcode** [comment]
See [this](https://github.com/BUAA-SE-Compiling/miniplc0-compiler/commit/da98ef2ae7c091d93a518f8deabe1698f48253a1#diff-933ae0e01ed62916e4ec1ba603285918).

issue 正文的链接请修改为 permanent links，不然不计入勘误。

请按照要求发送邮件给我们，感谢参与实验设计。
