### ISSUE TITLE
请问比如多一个end这种情况是不是没有考虑

### ISSUE THREAD

**Issue by 123liuziming** [BUAA-SE-Compiling/miniplc0-compiler#13]
比如说
begin
;
;
end
end
这种情况依然会编译通过，因为analyseProgram在读到end以后就退出去了，没有再读下一个end？

**Comment by wtdcode** [comment]
说出来你可能不信，十分钟前我们还讨论了这个问题。

其实这个问题最初就考虑过了，我们的意见是不管他，也就是说我们保证end只出现一次。

**Comment by 123liuziming** [comment]
砍需求爽爽爽

**Comment by 123liuziming** [comment]
砍需求爽爽爽
