### ISSUE TITLE
关于可以修改的内容以及辅助函数的问题

### ISSUE THREAD

**Issue by lynzrand** [BUAA-SE-Compiling/miniplc0-compiler#2]
_按照澪老师的指示把问题从论坛挪到这边来了_

---

在指导书中提到了

> 3.8.3.3 对修改的要求
>
> 为了方便测试，请务必注意在补全的时候是有一些限制的。
> 
> 你可以
> 
> ...
> 
> - 在 analyser.cpp 或者 tokenizer.cpp 的 miniplc0 命名空间下添加全局的辅助函数
> 
> ...
> 
> 你不能
> 
> - 修改除了上面提到的可修改文件以外的任何文件。
> 
> - 添加和删除任何文件。
> 
> - 修改 error.h 中除了 ErrorCode 取值以外的代码。
> 
> - 修改 fmts.hpp 中除了 ErrorCode 对应的 switch case 以外的代码。
> 
> - 修改 analyser.cpp 中 analyser***** 以外的函数。
> 
> - 修改 tokenizer.cpp 中 nextToken 以外的函数。
> 
> - ...
> 
> - 添加任何宏，包括但不限于 define, ifdef 等。
> 
> ...
> 

两个问题：

1. 可以添加全局辅助函数，但是 analyzer 和 tokenizer 的方法几乎全都是 private 的，也就意味着这些辅助函数不能使用这两个类的几乎所有方法和变量。不能添加宏顺便也堵死了用宏简化程序编写这条路。感觉限制可能有点太多了？

2. 自动代码格式化程序（尤其当格式化标准跟原本代码使用的不同时）会修改上面提到的“除...以外的函数”，甚至有可能修改其他不允许修改的文件（将所有文件全部格式化）。这种情况如何处理？有必要在最后提交前把修改的地方粘回原始代码库么？

---

一个示例的大概挺有用的辅助函数

```cpp
bool Analyser::tryExpectToken(const TokenType t) {
  auto x = nextToken();
  if (x.has_value() && x.value().GetType() == t) {
    return true;
  } else {
    unreadToken();
    return false;
  }
}
```

**Comment by wtdcode** [comment]
1. 限制的目标是为了保证能自动化评测，比如不允许添加类成员函数是为了保证类的签名不变，不允许添加宏是为了防止变形后编译错误，如果完全放开就意味着需要大量的手动评测，mini 和 C0 都这么搞精力不够。

2. 有，见[说明](https://github.com/BUAA-SE-Compiling/miniplc0-handbook/tree/8174750ab40eba35ed63c68bd6f0ae9484268e3a#3833-%E5%AF%B9%E4%BF%AE%E6%94%B9%E7%9A%84%E8%A6%81%E6%B1%82)

**Comment by lynzrand** [comment]
那请问一下评测的时候是把评测程序和变形之后的 miniplc0 代码库放在一起编译进行评测，还是说单独变形编译成一个动态链接库和 OJ 代码放在一起？如果是前者的话只要不修改任何现有函数的签名并且只添加 private 的辅助函数应该可以保证不需要修改评测代码吧（小声（瑟瑟发抖

**Comment by wtdcode** [comment]
这个问题很不好说，其实本质原因说实话是评测方案没有稳定。

编译静态库是考虑之一，但是更多的还是考虑直接源码编译，放开private函数的确可以，不过我需要一点时间评估一下。

**Comment by wtdcode** [comment]
@01010101lzy 也看一眼 #7

**Comment by wtdcode** [comment]
有点后悔了，早知道应用 pimpl 模式写的...

**Comment by wtdcode** [comment]
经过考虑
1. 今年大概不现实了，在考虑写一个 pimpl 版本的实现，反正肯定要放到明年了。
2. 答案依然不变。

**Comment by lynzrand** [comment]
> 
> 
> 经过考虑
> 
>     1. 今年大概不现实了，在考虑写一个 pimpl 版本的实现，反正肯定要放到明年了。
> 
>     2. 答案依然不变。

（前几天看见隔壁的隔壁 thu 要求要么 Java 要么 Rust 实现编译器，在想要不明年写一个 Rust 的吧（

> ![图片](https://user-images.githubusercontent.com/10259119/69213624-95d9b580-0b9f-11ea-84f7-a721154b46a3.png)
>
> ![图片](https://user-images.githubusercontent.com/10259119/69213586-7e9ac800-0b9f-11ea-9aaf-0b0171d789ff.png)
>
> ![图片](https://user-images.githubusercontent.com/10259119/69213605-8c504d80-0b9f-11ea-9d8e-2cc3d077e792.png)
