### ISSUE TITLE
Visual Studio 2019 打开CMake项目的问题

### ISSUE THREAD

**Issue by Asterism12** [BUAA-SE-Compiling/miniplc0-compiler#3]
直接用Visual Studio2019打开CMakeList.txt，加载完后会提示
_C++ IntelliSense信息可能过时，生成要刷新的CMake缓存。_
同时错误列表里对第5，6行
`add_subdirectory(3rd_party/argparse)`
`add_subdirectory(3rd_party/fmt)`
报错does not contain a CMakweList.txt file
请问应该如何解决？

**Comment by wtdcode** [comment]
https://github.com/BUAA-SE-Compiling/miniplc0-handbook/blame/8174750ab40eba35ed63c68bd6f0ae9484268e3a/Readme.md#L1093

实验课讲过了。

**Comment by Asterism12** [comment]
那份文档里的内容并未解决我的问题，google上也搜不到相应的解决方案，比较相似的是这一个搜索结果：
https://developercommunity.visualstudio.com/content/problem/243316/cmake-configuration-fails.html
但VS开发团队声称他们解决了这个BUG……

这是否是因为git pull出了问题？

**Comment by wtdcode** [comment]
你的到底是什么问题？submodule已经update了吗

________________________________

**Comment by Asterism12** [comment]
会到clone into ../3rd_party/fmt这步卡住……

**Comment by wtdcode** [comment]
网络问题，和 cmake 无关。

________________________________

**Comment by Asterism12** [comment]
感谢回复，之后开了v2ray，问题已解决
