### ISSUE TITLE
说一个坑，1G及1G以下内存的主机无法成功运行make

### ISSUE THREAD

**Issue by Asterism12** [BUAA-SE-Compiling/miniplc0-compiler#4]
会在
`Building CXX object CMakeFiles/miniplc0_test.dir/tests/test_main.cpp.o`
这一步卡住

需要自行加内存或者配置交换文件

**Comment by wtdcode** [comment]
复现一下 make VERBOSE=1 输出放到这里看看。

**Comment by Asterism12** [comment]
已经通过配置交换文件解决了，取消配置太麻烦所以……

之前make执行到此处会等一会然后报错：
`c++: fatal error: Killed signal terminated program cc1plus`
google一下说是内存不足

配置了2G的交换文件后make就可以完成了。

**Comment by wtdcode** [comment]
那估计可能真的是内存不足，但是你是在docker里还是宿主机make？

**Comment by Asterism12** [comment]
是在docker里

**Comment by wtdcode** [comment]
我在我电脑上试了下，开始编译前是1.89G占用，编译test_main.cpp.o的时候峰值是2.29，考虑到宿主机本身也需要不少内存还真有可能因为这个原因被杀掉....

虽然不算勘误但是也是个问题，按照格式发送邮件给我们吧。

感谢参与实验设计。

**Comment by wtdcode** [comment]
放在[这里](https://github.com/BUAA-SE-Compiling/miniplc0-handbook/blob/903ec7d3ca4670125fa466c41f8273418e06b36e/Readme.md#d22-windowsmac-%E6%80%8E%E4%B9%88%E5%8A%9E)了。
