### ISSUE TITLE
miniplc0进行词法/语法分析时-o参数不起作用

### ISSUE THREAD

**Issue by Zx55** [BUAA-SE-Compiling/miniplc0-compiler#5]
**以下在compilers-env中截图**

以语法分析-l为例
其中测试的in.plc0代码为
```
begin
    const a = -1;
    var b = 10;
    var c;
    c = b * a + 5;
    print(c);
end
```

![image](https://user-images.githubusercontent.com/37368558/68833449-6f72d080-06ee-11ea-8ed6-ed63be60b5f8.png)

于是我又换了不同的参数位置组合，如下图
![image](https://user-images.githubusercontent.com/37368558/68834242-418e8b80-06f0-11ea-8f1c-1374da1cae01.png)

奇怪的是我在clion中断点追踪，文件的的确确是打开了的（事实上out也被创建了）但是并没有被写入成功（之前似乎词法分析器是成功写入过，但现在也不行了）

![image](https://user-images.githubusercontent.com/37368558/68834543-02146f00-06f1-11ea-9f5a-14cdabe670c3.png)

请问是我使用姿势不对吗？

**Comment by wtdcode** [comment]
你把断点打在输出前，词法分析后看看。

________________________________

**Comment by Zx55** [comment]
> 你把断点打在输出前，词法分析后看看。

![image](https://user-images.githubusercontent.com/37368558/68835046-2c1a6100-06f2-11ea-94a0-f1498a934e08.png)

**Comment by wtdcode** [comment]
我记得output在传入之前会 ooen 一次，那里的确打开过了吗。

________________________________

**Comment by wtdcode** [comment]
打错了 是open

________________________________

**Comment by wtdcode** [comment]
算了 晚上来找我。

________________________________

**Comment by Zx55** [comment]
行

**Comment by wtdcode** [comment]
破案了，因为 exit(0) 导致 stream 的 close 没执行（完），所以没有输出。

非常漂亮的勘误，感谢参与实验设计，请按照格式发送邮件给我们。

**Comment by wtdcode** [comment]
我真是爱死C++了.jpg
