### ISSUE TITLE
关于Analyser::analyseConstantExpression是否要考虑溢出的问题

### ISSUE THREAD

**Issue by 123liuziming** [BUAA-SE-Compiling/miniplc0-compiler#6]
助教您好：

![92e788f3bacd07163086c4126e888763](https://user-images.githubusercontent.com/32130965/68857336-84b32380-071d-11ea-8de3-db2d9f290e76.png)

![a0655a381b5eabc33f7d0b010f8f8a45](https://user-images.githubusercontent.com/32130965/68857263-6baa7280-071d-11ea-8de4-2dcd3fbe2d0f.png)

在本次实验语法分析分析
<常表达式> ::= [<符号>]<无符号整数>时，注释里提示要注意是否溢出，但是我觉得貌似这里不用考虑溢出的问题，因为即使是最大的无符号整数2^31-1，取负号的时候也会变成-2^31+1，其实也不会溢出。如果真正出现溢出的情况在词法分析的时候就会返回一个空的Token的vector

我不知道我的想法是否正确，在此提出自己的疑惑，如果我的想法有误敬请助教谅解

**Comment by wtdcode** [comment]
好问题。

这里其实有一个设计问题，因为 tokenizer 返回的 token 存的是 int32_t，analyser 并不知道实际上它只存了 2^31-1 那么大，所以还是需要判断一下，不然的话 analyser 就跟 tokenizer 耦合了。

当然你们自己实现的时候就无所谓咯。

**Comment by 123liuziming** [comment]
明白了，谢谢助教
