### ISSUE TITLE
Analyser 的 analyse**** 函数是不是可以全部放开？

### ISSUE THREAD

**Issue by wtdcode** [BUAA-SE-Compiling/miniplc0-compiler#7]
想法来自 #2，需要尽快评估一下。

**Comment by lynzrand** [comment]
（这么说来咱好像改了不让改的函数）

**Comment by wtdcode** [comment]
那你编译分也被扬了

________________________________

**Comment by lynzrand** [comment]
等等，编译指导书里不是说可以重写所有的 `analyze.+` 函数吗，这个的意思是说可以自行添加此类函数？

**Comment by wtdcode** [comment]
草 钻漏洞带手字

________________________________

**Comment by wtdcode** [comment]
See [this](https://github.com/BUAA-SE-Compiling/miniplc0-handbook/commit/bf3ad759b1551bfad33508c455524f2431508b9e).
