### ISSUE TITLE
关于错误的类型

### ISSUE THREAD

**Issue by LemonForeast** [BUAA-SE-Compiling/miniplc0-compiler#8]
状态图中只出现了无符号整数，并没有有符号整数，而error.h中对应的溢出错误只有一个ErrIntegerOverflow, // int32_t overflow.
是不是少了一个无符号整数的溢出？

**Comment by wtdcode** [comment]
建议仔细阅读文法。

**Comment by fazdzz** [comment]
see [handbook #6](https://github.com/BUAA-SE-Compiling/miniplc0-handbook/issues/6)

并仔细阅读语义规则部分。
