### ISSUE TITLE
关于tokenizer.cpp中的checkToken函数的问题

### ISSUE THREAD

**Issue by Simoncxm** [BUAA-SE-Compiling/miniplc0-compiler#9]
在tokenizer.h中写了需要自己完成这个函数，但指导书中写只能修改nextToken函数。还是只能新增一个辅助函数用来检测其他情况？

**Comment by wtdcode** [comment]
没太理解你的问题。

**Comment by Simoncxm** [comment]
checkToken函数显然是应该补充其他情况的，但是指导书中写不能修改这个函数。

**Comment by Simoncxm** [comment]
比如检测一个数字是否越界是否可以也写在checkToken函数中？还是只能新建辅助函数

**Comment by wtdcode** [comment]
注意 Token 是 immutable 的。

也就是说如果你在 checkToken 内检查如果越界了，那只能重新创建一个新的 Token，从效率上来说不如直接 string 转 int 的时候就存好 int 或者返回错误，但是对于非法的 identifier 不存在这个问题。

这里准确来说是个设计遗留问题，可能的确放开 checkToken 会好一些，我需要一点时间评估一下。

**Comment by wtdcode** [comment]
See #11
